### PR TITLE
FLOE-4138: fixed file name for keyboard a11y tests

### PR DESCRIPTION
**Pull request by jobara**
Renamed keyboard a11y test files to follow the naming convention.

https://issues.fluidproject.org/browse/FLUID-4138

### CODE REVIEW

**Comment by cindyli** [comment]
Shall demos/keyboard-a11y directory also be renamed for consistency?

**Comment by jobara** [comment]
@cindyli, the underlying file is called jquery.keyboard-a11y.js. So I think it might make sense to leave the demo. We could also change the tests to be Keyboard-a11y-test.html and Keyboard-a11yTests.js. What do you think?

**Comment by cindyli** [comment]
I think it makes sense to change tests to be Keyboard-a11y-test.html and Keyboard-a11yTests.js

**Comment by jobara** [comment]
@cindyli renamed the files, ready for more review.

**Comment by cindyli** [comment]
The last commit message should use "FLUID-4138" rather than "FLOE-4138".

**Comment by jobara** [comment]
@cindyli this is ready for another round of review.

**Comment by cindyli** [comment]
Merged @ 47b15a3f8a2c16ee3474c7baf13c8a2798dce244

**Pull request merged**
