### PR TITLE
NOJIRA - Remove edit-hosts.sh hack

### PR DESCRIPTION
**Pull request by gtirloni**
This doesn't seem necessary anymore. All tests pass without it.

@avtar do you remember what failed because of this?

### CODE REVIEW

**Comment by avtar** [comment]
I think this was a workaround for a [Vagrant issue](https://github.com/hashicorp/vagrant/pull/6203) back in the day which was causing Ansible to freak out. It looks like Hashicorp addressed it with a later release.

**Comment by gtirloni** [comment]
@avtar thanks, it seems Ansible is fine with that now. Just a very minor cleanup then.

**Comment by gtirloni** [comment]
Ready for review.

**Comment by gtirloni** [comment]
Not a priority and too small for review. I'll remember to add it to a more substantial PR in the future to make more efficient usage of the review process.

**Pull request closed without merging**
