### PR TITLE
FLUID-6349: Fix timing info reported on QUnit's `testDone` event.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [FLUID-6349](https://issues.fluidproject.org/browse/FLUID-6349) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
This should address the "undefined ms" messages @jobara reported.  Rather than update the name and potentially break integration with things that are used to working with the older variable, I just reported the data twice, once under each name.

**Comment by jobara** [comment]
Just for clarification and correctness, @gtirloni first reported the issue.

**Comment by jobara** [comment]
@the-t-in-rtf it seems that after this change we are getting several `BadRequestError: request aborted`. This can be seen from https://ci.fluidproject.org/job/infusion-pr-browser-tests/113/console I ran it on my machine through vagrant and received the same errors. However, if I try the master branch, I don't get those errors.

**Comment by the-t-in-rtf** [comment]
@jobara, that problem has been coming up intermittently for ages and is not unique to this pull.  As an example, check out [this test run](https://ci.fluidproject.org/job/infusion-pr-browser-tests/100/console) from [Gio's pull](https://github.com/fluid-project/infusion/pull/923).

As far as we've seen, these errors do not interfere with test operation.  They also would likely require a lot of research to resolve, pulls against testem perhaps.  Rather than delay this very small pull that clearly fixes the timing issue, I'd suggest filing a ticket against gpii-testem with evidence (links to pulls). If the "bad request error" behaviour starts to result in false test failures or other problems, I can investigate.

**Comment by the-t-in-rtf** [comment]
It also is definitely happening in master, I just got this on a local run of `npm run test:vagrant` from master:

```
ok 69 Firefox 63.0 - [undefined ms] - Component Tests: /tests/component-tests/tooltip/html/Tooltip-test.html
BadRequestError: request aborted
    at IncomingMessage.onAborted (/home/vagrant/sync/node_modules/raw-body/index.js:231:10)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at abortIncoming (_http_server.js:439:9)
    at socketOnClose (_http_server.js:433:3)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
ok 70 Firefox 63.0 - [undefined ms] - Component Tests: /
```

**Comment by jobara** [comment]
Merged at d726d64d66e997f011077443047b005a9b344b19

**Pull request merged**
