### PR TITLE
FLUID-6401: Add editorconfig

### PR DESCRIPTION
**Pull request by greatislander**
This PR adds an initial EditorConfig file as per [FLUID-6401](https://issues.fluidproject.org/browse/FLUID-6401).

### CODE REVIEW

**Comment by jobara** [comment]
ok to test

**Comment by jobara** [comment]
@greatislander can you add the .editconfig file to the .npmignore.

**Comment by greatislander** [comment]
@jobara Done. Also renamed the PR to properly reflect the scope of the EditorConfig file.

**Comment by jobara** [comment]
@greatislander I just noticed that your last two commits are missing the JIRA number. Can you fix that or perhaps squash them all down into a single commit with the write commit comment style?

**Comment by greatislander** [comment]
Done @jobara.

**Comment by jobara** [comment]
merged at 78ce879d8ed1f27c8d1b392c4203827eb1891452

**Pull request merged**
