### PR TITLE
FLUID-6426: Fully working immutable options world

### PR DESCRIPTION
**Pull request by amb26**
This pull request depends on #968 and #824

### CODE REVIEW

**Comment by amb26** [comment]
@jobara - this is very nearly working but I wonder if you could take a look at the final TextToSpeech tests. The "Test utterance error" tests fails because the promise resolves before it rejects, but as far as I can see the race condition is real because there is always a chance that the utterance may finish? I tried finessing it by reducing the speech rate to 0.1 at https://github.com/fluid-project/infusion/pull/970/files#diff-db48edb1bc07eabb83304f3d98f2759cR338 but I still get the race fail.

**Comment by jobara** [comment]
@amb26 I've pushed an update to https://github.com/fluid-project/infusion/pull/968 that includes a fix for the failing test case. It looks like it wasn't actually a race condition, rather a problem with the IoC resolution. The utterances in the test are not passed to the speechsynthesis so they are never actually started. The test synthesizes the events through event dispatches. That means that the error case should only ever fire the error event. What seems to be have been happening is some confusion in the IoC resolution for `{utterance}` because the types for both components are `"fluid.tests.textToSpeech.utterance"`. The expression had been intended to match to the one with member name `utterance` but I think it was resolving to the `utteranceError` component member because of the last segment in the full type name. I could be mistaken about all this, but changing the member name and referencing that new name `utteranceSuccess` in the IoC expressions seems to have fixed the issues.

On a side note, I wasn't able to run this through testem because I was getting the following failure

```bash
22:05:52.283:  Stopping express...
22:05:52.284:  Express stopped...
22:05:52.286:  FATAL ERROR: Uncaught exception: options.lstat is not a function
TypeError: options.lstat is not a function
    at rimraf_ (/home/vagrant/sync/node_modules/gpii-testem/node_modules/rimraf/rimraf.js:135:11)
    at /home/vagrant/sync/node_modules/gpii-testem/node_modules/rimraf/rimraf.js:87:7
    at Array.forEach (<anonymous>)
    at afterGlob (/home/vagrant/sync/node_modules/gpii-testem/node_modules/rimraf/rimraf.js:86:13)
    at rimraf (/home/vagrant/sync/node_modules/gpii-testem/node_modules/rimraf/rimraf.js:63:12)
    at /home/vagrant/sync/node_modules/gpii-testem/src/js/testem-component.js:131:9
    at Object.invokeNext (/home/vagrant/sync/src/framework/core/js/FluidPromises.js:212:56)
    at Function.fluid.promise.resumeSequence (/home/vagrant/sync/src/framework/core/js/FluidPromises.js:192:39)
    at Function.fluid.promise.sequence (/home/vagrant/sync/src/framework/core/js/FluidPromises.js:226:23)
    at /home/vagrant/sync/node_modules/gpii-testem/src/js/testem-component.js:179:61
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! infusion@3.0.0 test:browser: `node node_modules/testem/testem.js ci --file tests/testem.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the infusion@3.0.0 test:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2019-11-21T22_05_52_321Z-debug.log
npm ERR! Test failed.  See above for more details.
Connection to 127.0.0.1 closed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! infusion@3.0.0 test:vagrant: `vagrant up && vagrant ssh -c 'cd /home/vagrant/sync/; DISPLAY=:0 npm test'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the infusion@3.0.0 test:vagrant script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jo/.npm/_logs/2019-11-21T22_05_51_255Z-debug.log
```

**Comment by jobara** [comment]
@amb26 it seems the CI is failing with the same testem error I mentioned in my comment above.

**Comment by amb26** [comment]
Closed for #972, this was issued under the wrong JIRA

**Pull request closed without merging**
