### PR TITLE
FLUID-6392: Only calling cancel when disabling.

### PR DESCRIPTION
**Pull request by jobara**
https://issues.fluidproject.org/browse/FLUID-6392

Needed to address https://issues.gpii.net/browse/GPII-3977. A dev release of Infusion has also been generated ( 3.0.0-dev.20190807T173919Z.741f09ead.FLUID-6392 ) for testing.

### CODE REVIEW

**Comment by jobara** [comment]
@amb26 would you mind to review this PR?

**Comment by amb26** [comment]
Strange failure through "abort"... 
ok 205 Chrome 76.0 - [1448 ms] - Framework Tests: /tests/framework-tests/preferences/html/SelfVoicingEnactor-test.html
Build was aborted
Aborted by unknown
Killed by signal 15.

**Comment by amb26** [comment]
ok to test

**Comment by jobara** [comment]
@amb26 ready for another round of review.

**Comment by jobara** [comment]
> Strange failure through "abort"...
> ok 205 Chrome 76.0 - [1448 ms] - Framework Tests: /tests/framework-tests/preferences/html/SelfVoicingEnactor-test.html
> Build was aborted
> Aborted by unknown
> Killed by signal 15.

Could it be related to https://issues.fluidproject.org/browse/FLUID-6385 Although I haven't personally seen this issue trigger anywhere but the current version of MS Edge.

**Comment by jobara** [comment]
ok to test

**Pull request merged**
