### PR TITLE
FLUID-5831: Corrected broadcast of storeType so that it properly displaces default and test grades

### PR DESCRIPTION
**Pull request by amb26**
@acheetham - here's the fix for the "storeType" issue we discussed earlier

### CODE REVIEW

**Comment by acheetham** [comment]
@amb26, just noticing that the JIRA number in your commit log has some digits transposed...

**Comment by acheetham** [comment]
@amb26, I've tried this change in my sample code - works beautifully. Specifying a custom store is very straightforward now, and seems quite reasonable, from an integrator's perspective.

**Comment by jobara** [comment]
@amb26 the commit log has the wrong JIRA number. It should have been FLUID-5831. You should be able to correct this with `git commit --amend` or `git reset --soft` and then push back up with `git push origin -f`.

**Comment by jobara** [comment]
@amb26 the UIO demo is broken, and it has the "gear" icon in the bottom right of the page, which i guess is for the Infusion debugger thing.

**Comment by amb26** [comment]
Thanks, @jobara - I've corrected both the commit comment and the demo failure

**Comment by jobara** [comment]
merged at e51c67226e2aa7a758e1a2c364d2448dbe947539

**Pull request merged**
