### PR TITLE
NOJIRA - Fix Ansible inventory warning

### PR DESCRIPTION
**Pull request by gtirloni**
Ansible used to include an inventory file that had "localhost". The default inventory now is empty and this warning is shown:

```
    default:  [WARNING]: provided hosts list is empty, only localhost is available. Note
    default: that the implicit localhost does not match 'all'
```

This shows in red in log output and can confuse users.

I'm proposing an inventory is defined on the fly through a command line parameter, just to satisfy Ansible and clean up the logs. This should be harmless.

### CODE REVIEW

**Comment by gtirloni** [comment]
@jobara @avtar could you help review this PR? Thanks!

**Comment by gtirloni** [comment]
This change was also introduced in GPII's [universal](https://github.com/GPII/universal/pull/603), [nexus](https://github.com/GPII/nexus/pull/13) and [linux](https://github.com/GPII/linux/pull/98) repositories.

**Comment by jobara** [comment]
@avtar would you like to sign off on this. I can merge if you think it all looks good.

**Comment by jobara** [comment]
merged at 74190ef200e64cebd0451b2493883db2e20c96e0

**Comment by gtirloni** [comment]
Thanks @jobara and @avtar

**Pull request merged**
