### PR TITLE
FLUID-6327: Improve lint time.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [FLUID-6327](https://issues.fluidproject.org/browse/FLUID-6327) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
@amb26, this pull fixes the lint speed.  IMO this should be reviewed after the associated [globbing](https://github.com/GPII/gpii-glob/pull/1) and [gpii-grunt-lint-all](https://github.com/GPII/gpii-grunt-lint-all/pull/6) pulls.

**Comment by the-t-in-rtf** [comment]
@amb26, once the tests pass we should merge this to improve the lint speed in master.

**Comment by the-t-in-rtf** [comment]
OK, looks like we're good to go.

**Comment by jobara** [comment]
merged at 81c4c0572b8ac0ffd650fa675cc8dab43d422d11

**Pull request merged**
