### PR TITLE
FLUID-6247: Update to add JSDocs linting and fix linting errors.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [FLUID-6247](https://issues.fluidproject.org/browse/FLUID-6247) for details.

### CODE REVIEW

**Comment by amb26** [comment]
I'm a bit lost since I swear I saw the buildkite build for this pull failing before, due to a back-version of kettle being demanded via gpii-testem -> gpii-express, but somehow it seems to have magically gone away without any update to the gpii-testem version. Have I become horribly confused or am I imagining things?

**Comment by amb26** [comment]
Hi, thanks for this great work on improving our linting. Somehow, I found that I was unable to get the new linting rule to do anything. Despite pulling in the eslint-config-fluid from the dev release 1.2.0-dev.20180213T130610Z.40e6281 , I am unable to provoke any JSDoc errors through mangling comments, e.g. in src\framework\core\js\FluidIoC.js by, for example, omitting trailing }, using invalid types, or converting the banner comments back to /** . Can you think what might be going wrong?

**Comment by the-t-in-rtf** [comment]
We should pair on this, because I can immediately see problems if I remove a trailing brace or use a wildly invalid type (such as "total nonsense").  You might also comment on what you meant by this chat:

> NOW it suddenly starts linting 20:15
> Now I checked out a completely different branch

The banners are another story, my previous experience led me to believe we needed to be stricter with those than actually appears to be the case.  As far as I can see, banners that begin and end with double-asterisks are only a problem if they are positioned immediately above a function that takes arguments and/or returns a value.  See this example, which still lints if I remove the spaces:

https://github.com/the-t-in-rtf/infusion/blob/FLUID-6247/src/framework/core/js/FluidIoC.js#L1609

The previous example doesn't complain because the function neither takes arguments nor returns anything.  We should still separate that with a carriage return, IMO, as otherwise it looks like it's the JSDoc for the next function.

Most of the banners in FluidIoC.js are separated from the next function by a carriage return, and so don't throw an error even if the next function has arguments or returns a value.

I'll go through and clean up the escaped banners a bit with this new knowledge.

**Comment by the-t-in-rtf** [comment]
I merged with upstream/master and fixed the additional linting errors brought in by same.

**Comment by the-t-in-rtf** [comment]
@amb26, I suspect this will "just work" once we merge [FLUID-6256](https://github.com/fluid-project/infusion/pull/879).  We should pause this one until that one is merged.

**Comment by the-t-in-rtf** [comment]
OK, following the merge of the "hardening" work, I still see the same error on the AuxBuilder tests that shows up in CI:

```
Died on test #1 @http://localhost:7357/tests/framework-tests/preferences/js/BuilderTests.js:764:5
@http://localhost:7357/tests/framework-tests/preferences/js/BuilderTests.js:15:2
: fetchPromise is undefined
Source: 	

fluid.pageEnhancer.init@http://localhost:7357/src/framework/preferences/js/UIEnhancer.js:1:5152
togo@http://localhost:7357/src/framework/core/js/FluidIoC.js:1:305903
fire@http://localhost:7357/src/framework/core/js/Fluid.js:1:266893
fluid.initComponent@http://localhost:7357/src/framework/core/js/Fluid.js:1:319261
creator@http://localhost:7357/src/framework/core/js/Fluid.js:1:288285
fluid.invokeGlobalFunction@http://localhost:7357/src/framework/core/js/Fluid.js:1:249426
fluid.initSubcomponentImpl@http://localhost:7357/src/framework/core/js/Fluid.js:1:319840
fluid.initDependent@http://localhost:7357/src/framework/core/js/FluidIoC.js:1:283618
fluid.initDependents/<@http://localhost:7357/src/framework/core/js/FluidIoC.js:1:287481
fluid.each@http://localhost:7357/src/framework/core/js/Fluid.js:1:228912
fluid.initDependents@http://localhost:7357/src/framework/core/js/FluidIoC.js:1:287392
fluid.initComponent@http://localhost:7357/src/framework/core/js/Fluid.js:1:318346
creator@http://localhost:7357/src/framework/core/js/Fluid.js:1:288285
fluid.invokeGlobalFunction@http://localhost:7357/src/framework/core/js/Fluid.js:1:249426
fluid.prefs.create@http://localhost:7357/src/framework/preferences/js/Builder.js:1:9960
@http://localhost:7357/tests/framework-tests/preferences/js/BuilderTests.js:765:37
run@http://localhost:7357/tests/lib/qunit/js/qunit.js:207:4
run/<@http://localhost:7357/tests/lib/qunit/js/qunit.js:365:5
process@http://localhost:7357/tests/lib/qunit/js/qunit.js:1457:4
start/<@http://localhost:7357/tests/lib/qunit/js/qunit.js:483:5
```
I'm investigating further now.

**Comment by the-t-in-rtf** [comment]
@amb26, we are now back to sane test results, including in CI.  This should be ready for final review and hopefully to merge.

**Pull request merged**
