### PR TITLE
Removed extra div in Image Reorder

### PR DESCRIPTION
**Pull request by prastut**

### CODE REVIEW

**Comment by colinbdclark** [comment]
Hi @prastut, thanks for the pull request! I'm wondering if you can provide a bit more detail about the rationale for this particular change? I don't see a description or accompanying JIRA ticket (https://issues.fluidproject.org) that describes the motivation for the fix.

**Comment by colinbdclark** [comment]
Ah, I see from the name of your branch that it must be in reference to this JIRA, is that right? https://issues.fluidproject.org/browse/FLUID-3258

**Comment by prastut** [comment]
Yup. It is for the issue for the link you have provided. 
How can I make the PR procedure as swift as possible?

**Comment by amb26** [comment]
Hi @prastut - did you test your fix to make sure it works?

**Comment by prastut** [comment]
Hi @amb26 that is what I wanted to ask (had asked on IRC too). I was running it manually, how to run a build server? I ran "grunt" and all tests were seem to passing. Since it's just a removal of div, do we need to test it too? If we are, can you guide me how to write one in such a case?

**Comment by amb26** [comment]
Since this is a demo, it is not covered by the test suite testing the core framework. The instructions for testing it are contained in the demo markup itself: https://github.com/prastut/infusion/blob/FLUID-3258/demos/reorderer/imageReorderer/index.html#L53

**Comment by prastut** [comment]
How do you actually run the webapp? I did a grunt serve which doesn't do anything.

**Comment by jobara** [comment]
@prastut for this particular demo you may be able to just run the demo from the local file system. That is paste the path to the index.html file you modified into your browsers and follow along with the tests outlined in this manual test plan https://wiki.fluidproject.org/display/fluid/Reorderer+QA+Test+Plan+-+Image+Reorderer. For any demo that uses any AJAX requests you'll need to run the demo through a web server. Infusion does not come with it's own web server, but there are many  you could use such as [MAMP](https://www.mamp.info/en/), [WAMP](http://www.wampserver.com/en/), [Grunt Connect](https://github.com/gruntjs/grunt-contrib-connect), [SimpleHTTPServer](http://www.linuxjournal.com/content/tech-tip-really-simple-http-server-python), [node http-server](https://www.npmjs.com/package/http-server), and etc.

**Comment by jobara** [comment]
@prastut thank you for your pull request. We ask that all our contributors sign a CLA. Could you please fill out the Fluid CLA and send it to me. https://wiki.fluidproject.org/display/fluid/Fluid+Licensing You can ping me in the IRC channel (Justin_o) if you have more questions on that.

For background reading, here's a good overview of what CLAs are and why they're important: http://oss-watch.ac.uk/resources/cla

**Comment by jobara** [comment]
@prastut are you still interested in working on this pull request and could you provide us with a CLA?

**Comment by jobara** [comment]
@prastut I'm closing this due to inactivity. If you have time to work on it again feel free to open a new pull request.

**Pull request closed without merging**
