### PR TITLE
FLUID-6325: Moving to a centralized file for maintaining copyright

### PR DESCRIPTION
**Pull request by jobara**
For cases where code was forked from another location, I've retained the original copyright holder information in the file scope.

https://issues.fluidproject.org/browse/FLUID-6325

### CODE REVIEW

**Comment by jobara** [comment]
@colinbdclark and @amb26  could you please review this PR?

**Comment by colinbdclark** [comment]
@jobara and I reviewed and talked about this PR together today, and we agreed that a) it looks great and b) we'll make these minor changes:
* For our list of contributors, we will link to the Github Contributors page for the repository, which should provide an accurate list based on the current state of the code—and better yet, we won't have to keep it up to date by hand.
* We'll remove dates from the copyright statement header in each file, to reduce the amount of ongoing maintenance.
* We'll change the attribution in the header to "The Infusion copyright holders"
* We'll cross-reference the Author section with the commits in the Contributors page and ensure that attributed authors are up-to-date.

**Comment by jobara** [comment]
@colinbdclark this is ready for another round of review.

**Comment by colinbdclark** [comment]
Thanks, @jobara!

**Pull request merged**
