### PR TITLE
Fluid-5874: Text overlaps on headers when default theme is used.

### PR DESCRIPTION
**Pull request by lemetice**
Hi everyone!,
I created an issue on JIRA but could not assign it to myself but I solve the bug and wish to merge to master.

### CODE REVIEW

**Comment by jobara** [comment]
@lemetice thank you for your pull request. We ask that all our contributors sign a CLA. Could you please fill out the Fluid CLA and send it to me. https://wiki.fluidproject.org/display/fluid/Fluid+Licensing You can ping me in the IRC channel (Justin_o) if you have more questions on that.

For background reading, here's a good overview of what CLAs are and why they're important: http://oss-watch.ac.uk/resources/cla

**Comment by lemetice** [comment]
Hi @jobara , 
The pull request by @lemetice is mind. That's my user name on github. 
JIRA: Awesome Arnold 
IRC : Awesome_A
Same email everywhere :arnoldtagne@gmail.com

**Comment by jobara** [comment]
@lemetice ah thanks for the clarification and for sending in the CLA.

**Comment by jobara** [comment]
@lemetice could you update the commit logs to comply with the [coding and commit standards](https://wiki.fluidproject.org/display/fluid/Coding+and+Commit+Standards).

GitHub help has information on how to amend commit messages.
https://help.github.com/articles/changing-a-commit-message/

**Comment by lemetice** [comment]
This pull request has been close because the commit logs to did not comply with the 
 
[coding and commit standards](https://wiki.fluidproject.org/display/fluid/Coding+and+Commit+Standards).

**Pull request closed without merging**
