### PR TITLE
FLUID-6555: Use fluid-grunt-lint-all for linting.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [FLUID-6555](https://issues.fluidproject.org/browse/FLUID-6555) for details.

cc: @amb26

### CODE REVIEW

**Comment by amb26** [comment]
Mysteriously this pull does not work for me - massive failures across the board with redeclared variables and indentation - 
````
E:\source\gits\infusion-master\tests\test-core\utils\js\IoCTestUtils.js
   16:5  error  'fluid_3_0_0' is already defined as a built-in global variable  no-redeclare
  245:1  error  Expected indentation of 24 spaces but found 21                  indent
  247:1  error  Expected indentation of 24 spaces but found 21                  indent
  462:1  error  Expected indentation of 20 spaces but found 19                  indent

? 803 problems (801 errors, 2 warnings)
  546 errors and 0 warnings potentially fixable with the `--fix` option.
````
I've tried blowing away node_modules and reinstalling

**Comment by the-t-in-rtf** [comment]
Just to confirm, what version of node/npm do you have?  The lint checks pass in CI with 10/12, and pass for me with 14, or I wouldn't have been able to commit to create the pull.

**Comment by amb26** [comment]
It turns out that I had a stale version of fluid-grunt-lint-all as some hangover corruption from testing @jobara 's https://github.com/jobara/fluid-grunt-lint-all/tree/issue-14 - horrifyingly this can survive rm -rf node_modules and stayed until I deleted my package-lock.json file - another great reason not to have such a monstrosity. The confusion arises since the stale version has a matching version number - this pull is fine

**Comment by jobara** [comment]
> It turns out that I had a stale version of fluid-grunt-lint-all as some hangover corruption from testing @jobara 's https://github.com/jobara/fluid-grunt-lint-all/tree/issue-14 - horrifyingly this can survive rm -rf node_modules and stayed until I deleted my package-lock.json file - another great reason not to have such a monstrosity. The confusion arises since the stale version has a matching version number - this pull is fine

This is interesting, well scary. Why did they have the same version number? Did you test using `npm link` or some other method?

**Comment by amb26** [comment]
They have the same version number since the version in package.json in your pull request is unchanged from the latest one release by npm - in these cases it looks like npm will simply believe what it sees there - a big reason to avoid git-based dependencies even transiently : P

**Pull request merged**
