### PR TITLE
overlapping text  handled 

### PR DESCRIPTION
**Pull request by amanvar**
This issue resolved [FLUID-5874](https://issues.fluidproject.org/browse/FLUID-5874).
text overlapping resolved
Please have a look
feedback welcome

### CODE REVIEW

**Comment by lemetice** [comment]
Great @amanvar .Well did you tried that on other browsers ? 
I solved the bug by adding some (-webkit-padding) on "p tag" in the columns and works well  on chrome browser.

**Comment by amanvar** [comment]
Yeah I tried it in firefox as well as in chrome browser. It works fine for both browser.

**Comment by jobara** [comment]
@amanvar thank you for your pull request. We ask that all our contributors sign a CLA. Could you please fill out the Fluid CLA and send it to me. https://wiki.fluidproject.org/display/fluid/Fluid+Licensing You can ping me in the IRC channel (Justin_o) if you have more questions on that.

For background reading, here's a good overview of what CLAs are and why they're important: http://oss-watch.ac.uk/resources/cla

**Comment by amanvar** [comment]
@jobara ok, I will ask you if I have some question regarding CLA.
Thanks

**Comment by jobara** [comment]
@amanvar also could you update the pull request name and the commit log to comply with the [coding and commit standards](https://wiki.fluidproject.org/display/fluid/Coding+and+Commit+Standards).

GitHub has information on how to amend a commit message.
https://help.github.com/articles/changing-a-commit-message/

**Comment by amanvar** [comment]
@jobara I deleted my branch on which I was working. So I cannot work on this PR. I created another PR #692. So, can we please work on that PR.

**Comment by jobara** [comment]
Closing in favour of https://github.com/fluid-project/infusion/pull/692 as per @amanvar's comment.

**Pull request closed without merging**
