### PR TITLE
FLUID-6140: Improvements to Infusion's auto-self-deduping to allow it to function as a dependency of one of its own devDependencies

### PR DESCRIPTION
**Pull request by amb26**
@the-t-in-rtf - this is a trial fix with some extra diagnostics in - I seemed to be able to use it to run your FLUID-6139, please try it out and see if it works for you - cheers!

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
Thanks, @amb26, I merged your branch with mine and confirmed that gpii-testem can successfully require infusion.

**Comment by the-t-in-rtf** [comment]
OK, I had to cut a new dev release of gpii-testem that uses your branch of infusion.  The testem tests now run using gpii-testem.

**Comment by the-t-in-rtf** [comment]
@amb26, is there a dev release with this fix in it?

**Comment by the-t-in-rtf** [comment]
Thanks @amb26.  I updated both gpii-express and gpii-testem to use the dev release, after which "fluid.require" works as expected when run from the root of the v: drive.

**Comment by the-t-in-rtf** [comment]
I commented twice, but just to cross-link for the context.  The JIRA issue associated with this PR is [FLUID-6140](https://issues.fluidproject.org/browse/FLUID-6140).

**Comment by cindyli** [comment]
Merged at 5e835f6114ab60444ff65d5bcc7c5b0f8bb28873

**Pull request merged**
