### PR TITLE
FLUID-6610: Restrict part of model checked in SeparatedPanelPrefsEditorTests.js

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by jobara** [comment]
@amb26 could you please remove the mention of normalize from the readme. I think it's still mentioned as a build module.

**Comment by amb26** [comment]
> @amb26 could you please remove the mention of normalize from the readme. I think it's still mentioned as a build module.

It's gone

**Comment by jobara** [comment]
Buttons on the textfield stepper are smaller than they used to be (Tested in FF 87 macOS 11).

In main ([Prefs Framework demo](https://build-infusion.fluidproject.org/demos/prefsframework/)):
Screen Shot 2021-03-31 at 8 08 08 AM

In this PR:
Screen Shot 2021-03-31 at 8 07 56 AM

**Comment by amb26** [comment]
> Buttons on the textfield stepper are smaller than they used to be (Tested in FF 87 macOS 11).

I assume this issue is also in #1042

**Comment by jobara** [comment]
Changes from this PR have been migrated to https://github.com/fluid-project/infusion/pull/1042 and will be merged with that one.

**Pull request closed without merging**
