### PR TITLE
FLUID-5982: Allow injected components to be designated via expanders

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by michelled** [comment]
@amb26: @jobara is waiting on either more tests or an explanation on why they aren't needed for this pull request

**Comment by amb26** [comment]
Hi @jobara - I'm not quite sure what you mean. The targetComponent isn't instantiated here - the expander designates that the already instantiated component "sourceComponent" should be injected in its place. So as far as I can see, we test the functionality that is implemented.

**Comment by jobara** [comment]
@amb26 I guess I mean is it a real component versus just having the options copied over, but I think i see that it access it off of that. So perhaps that is enough. However I have some more questions about how it works and things that could be tested.

- Does targetComponent act as an alias for sourceComponent? If i make a change to a member in one, does it change the other? 
- Do they have the same component ID's?

**Comment by amb26** [comment]
@jobara - http://docs.fluidproject.org/infusion/development/SubcomponentDeclaration.html#injected-subcomponent-declaration

**Comment by jobara** [comment]
merged at de9be1200c491fed7d951298ad866de54ef7f7e7

**Pull request merged**
