### PR TITLE
FLUID-4728 : Resolved hovering issue of the disabled Add button

### PR DESCRIPTION
**Pull request by NRDa27**
Resolved hovering issue of the Add button while the files in the queue are being uploaded.

### CODE REVIEW

**Comment by jobara** [comment]
@NRDa27  could you please amend your commit log to include the JIRA number at the beginning.  And the commit log should also summarize the change.

See:

* https://wiki.fluidproject.org/display/fluid/Coding+and+Commit+Standards#CodingandCommitStandards-JIRAandgithub
* https://help.github.com/articles/changing-a-commit-message/

**Comment by cindyli** [comment]
@NRDa27 this change seems removing the grey box from the hover styling for all cases even when the button is enabled and the grey box should be shown. See the screen shot below where the grey box is supposed to but not shown on an enabled "browse file" button.

screen shot 2016-03-09 at 12 35 22 pm

**Comment by jobara** [comment]
@NRDa27 in regards to the Commit message, thanks for adding the JIRA number, but you still need to include a full description of what was changed in the commit. 

See: [Commit Logs](https://wiki.fluidproject.org/display/fluid/Coding+and+Commit+Standards#CodingandCommitStandards-CommitLogs)

**Comment by jobara** [comment]
@NRDa27 did you see my last message about updating the commit log to include a full description?

**Comment by cindyli** [comment]
@NRDa27 the previous issue is persistent that your css change removes the hover styling not only when the "browse file" button is disabled, but also when it is enabled, which is incorrect.

**Comment by cindyli** [comment]
@NRDa27, do you plan to continue working on this pull request? If not, this pull request will be closed due to its inactivity.

**Comment by cindyli** [comment]
Closed as an inactive pull request.

**Pull request closed without merging**
