### PR TITLE
FLUID-5922 - Upgrade to Fedora 24

### PR DESCRIPTION
**Pull request by gtirloni**
To test, retrieve this PR and run:

```
vagrant up
grunt tests
```

### CODE REVIEW

**Comment by gtirloni** [comment]
@fluid-project/maintainers - in order to test this PR, you'll need the changes from FLUID-5932 (#729)

**Comment by avtar** [comment]
Hey Gio, if you get time tomorrow could you please update your PR to also disable 3D acceleration?

```
diff --git a/Vagrantfile b/Vagrantfile
index d7fb14e..a128e1f 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -24,7 +24,7 @@ ram = ENV["VM_RAM"] || 2048

 Vagrant.configure(2) do |config|

-  config.vm.box = "inclusivedesign/fedora23"
+  config.vm.box = "inclusivedesign/fedora24"

   # Your working directory will be synced to /home/vagrant/sync in the VM.
   config.vm.synced_folder ".", "#{app_directory}"
@@ -47,8 +47,8 @@ Vagrant.configure(2) do |config|
   config.vm.provider :virtualbox do |vm|
     vm.customize ["modifyvm", :id, "--memory", ram]
     vm.customize ["modifyvm", :id, "--cpus", cpus]
-    vm.customize ["modifyvm", :id, "--vram", "128"]
-    vm.customize ["modifyvm", :id, "--accelerate3d", "on"]
+    vm.customize ["modifyvm", :id, "--vram", "256"]
+    vm.customize ["modifyvm", :id, "--accelerate3d", "off"]
     vm.customize ["modifyvm", :id, "--audio", "null", "--audiocontroller", "ac97"]
     vm.customize ["modifyvm", :id, "--ioapic", "on"]
     vm.customize ["setextradata", "global", "GUI/SuppressMessages", "all"]
```

Thanks!

**Comment by avtar** [comment]
@jobara You'll probably want to run ``grunt tests`` to test this. As mentioned earlier I've been using these changes with the Sauce Labs work and the VM works as expected.

**Comment by jobara** [comment]
merged at 6402887bfb4bc560d2aa15999364702d6b6ca4f0

**Comment by gtirloni** [comment]
@jobara awesome, thank you!

**Pull request merged**
