### PR TITLE
FLUID-6607: remove normalize.css dependency

### PR DESCRIPTION
**Pull request by greatislander**
This PR required minimal CSS changes, as follows:

- In several components and throughout demos, `button`, `input`, and `select` elements were given the following CSS to preserve their expected font family and size: `font-family: inherit; font-size: 100%`.
- In the separated panel preferences editor stylesheet, a `margin: 0` rule was added to the `body` element to preserve the prefs editor panel's position flush at the top of the window.

### CODE REVIEW

**Comment by greatislander** [comment]
Not sure why this test is failing: https://github.com/fluid-project/infusion/blob/ca1e594bd6883a5e002a50bb77521c5ecfd35fc0/tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorTests.js#L148-L150

**Comment by amb26** [comment]
I can't reproduce this failure in Firefox on Windows. I checked that the tests are properly using the "temporary" in-memory store so there shouldn't be any possibility for the store behaviour to be platform-dependent.

**Comment by amb26** [comment]
What's extremely mysterious is that the failure in this branch is consistent - I've rerun the tests 3 times now, and on the other hand the pass in #1043 is also consistent which I've rerun twice

**Comment by jobara** [comment]
I was able to reproduce this in FF on macOS, although not consistently.

It seems to be an issue with the panelIndex being included sometimes.

```JSON
{   
    "panelIndex": 0,  
    "preferences": {     
        "lineSpace": 2,     
        "textFont": "verdana",     
        "textSize": 1.8,     
        "theme": "bw"   
    } 
}
```

**Comment by greatislander** [comment]
> It seems to be an issue with the panelIndex being included sometimes.

That's very odd. As far as I can tell the only changes my PR makes are removing Normalize from the module dependencies and HTML files and a couple of small CSS adjustments. That test failure is a very bizarre side effect.

**Comment by amb26** [comment]
> It seems to be an issue with the panelIndex being included sometimes.

Thanks for the great investigation, @jobara - the "old" framework was pretty racy with model updates and so a small change in rendering timings may mean that the initial rendering races differently with the preferences updates. I think that the soundest update would be to adjust the test so that it only compares the preferences part of the model - I've written up this issue at https://issues.fluidproject.org/browse/FLUID-6610

**Comment by jobara** [comment]
@amb26 and @greatislander some more info. It seems the panelIndex change is coming from [onScroll](https://github.com/fluid-project/infusion/blob/4e804fee39403575f893565548124f6e61b00490/src/framework/preferences/js/ArrowScrolling.js#L102-L111) event listener. This doesn't seem to fire in main, but does trigger from this branch.

**Comment by jobara** [comment]
@amb26 and @greatislander it might be related to `fluid.prefs.arrowScrolling.scrollToPanel` which will attempt to [scroll](            scrollContainer.scrollLeft(scrollContainer.scrollLeft() + panels.eq(panelIndex).offset().left);) the container to the left to the specified panel.

**Comment by jobara** [comment]
There's a strange issue with the overview panel in the Prefs framework demo. When the line space increase from 1.0 to 1.1 the line space in the overview panel actually decreases. Increasing the linespace further does increase the spacing. This isn't an issue in main.

**Comment by greatislander** [comment]
> Moving a comment I filed [#1045 (comment)](https://github.com/fluid-project/infusion/pull/1045#issuecomment-811020214)
> 
> There's a similar issue with the toggle switch inputs. These can be seen in the same prefs framework demo.

This is now resolved.

**Comment by jobara** [comment]
@greatislander could you please merge this with main?

**Comment by jobara** [comment]
In Safari 14.0.3 (macOS 11), the Orator's "Play" button is smaller than the icon to the left. 

In the [Orator demo](https://build-infusion.fluidproject.org/demos/orator/) from main:
Screen Shot 2021-04-01 at 8 49 45 AM

In the Orator demo from this PR:
Screen Shot 2021-04-01 at 8 49 39 AM

**Comment by greatislander** [comment]
> In Safari 14.0.3 (macOS 11), the Orator's "Play" button is smaller than the icon to the left.

This is fixed now, @jobara.

**Comment by jobara** [comment]
merged at f346ada4eefc1b056c35aaab39885e87285c3594

**Pull request merged**
