### PR TITLE
FLUID-6290 - Upgrade to Fedora 28 vagrant box

### PR DESCRIPTION
**Pull request by gtirloni**

### CODE REVIEW

**Comment by gtirloni** [comment]
Ready for review.

**Comment by gtirloni** [comment]
Not a priority. Closing.

**Comment by gtirloni** [comment]
Reopening to test against latest F28 box (20180820)

**Comment by gtirloni** [comment]
Fedora 27 will go out of support when Fedora 29 is released.

F29 is scheduled to be released on 10/23 (see [docs](https://fedoraproject.org/wiki/Releases/29/Schedule)). By that time it'd be nice to have migrated to F28.

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by jobara** [comment]
Merged at 2060e79ff43769fe98bc1b53cfcd8a6d7c7a9c12

**Pull request merged**
