### PR TITLE
FLUID-6505: restore focus style to text style input box

### PR DESCRIPTION
**Pull request by greatislander**
This should resolve [FLUID-6505](https://issues.fluidproject.org/projects/FLUID/issues/FLUID-6505). @cindyli, can you test this branch locally and see if it addresses the issue?

### CODE REVIEW

**Review by cindyli — APPROVED** [review]
Tested with latest firefox, chrome and safari on Mac. This PR does fix the problem.

**Comment by jobara** [comment]
@greatislander is this still an issue? Did you fix this already with the Sass conversion?

**Comment by greatislander** [comment]
I did not, I'll update it.

**Comment by greatislander** [comment]
@jobara Done. Also I realized that the contrast theme colours were not being used to style the focus ring around the contrast theme selection (ironically). Fixed this in ba1f7d5.

**Review by cindyli — APPROVED** [review]

**Comment by cindyli** [comment]
Retested in firefox, chrome and safari on Mac. This PR looks and works great.

**Comment by greatislander** [comment]
@cindyli If you're good with this, can you merge it?

**Pull request merged**
