### PR TITLE
FLUID-6582 Add pt_BR localization to preferences messages

### PR DESCRIPTION
**Pull request by gtirloni**

### CODE REVIEW

**Comment by gtirloni** [comment]
I checked the output of codecov and it's suggesting I made changes to files that I didn't really change (e.g. Orator.js). I'm not sure what it's comparing against.

**Comment by jobara** [comment]
> I checked the output of codecov and it's suggesting I made changes to files that I didn't really change (e.g. Orator.js). I'm not sure what it's comparing against.

I'm re-running the tests. I have a theory that some of the tests that have conditionals are having their checks time out in some runs and thus not running all of the tests and causing the coverage to drop.

**Comment by jobara** [comment]
@gtirloni would you be able to add a translation for the simplify adjuster? It's currently only in the prefs framework demo, but we'd like to make a real preference and adjuster for it at some point. 

see: https://github.com/fluid-project/infusion/tree/main/demos/prefsFramework/messages

**Comment by gtirloni** [comment]
> @gtirloni would you be able to add a translation for the simplify adjuster?

Done!

**Comment by jobara** [comment]
Merged at 39773eb69938b6fa0bb9e3ae8f083775d2754f2f

**Pull request merged**
